### ISSUE TITLE
[Sub-task] Create the Icons

### ISSUE THREAD

**Issue by OlgaOrtiz** [OlgaOrtiz/Nekos-Magic-Converter#23]
# What do we need?
Observe and develop illustrations of cats for the different types of convertibles: weight, length, temperature and currency.

# Acceptance Criterial
- [ ] Creating weigth icon
- [ ] Creating length icon
- [ ] Creating temperature icon
- [ ] Creating coin icon

# Upgrades not necessary
- [ ] Creating weigth gif
- [ ] Creating length gif
- [ ] Creating temperature gif
- [ ] Creating coin gif
