### ISSUE TITLE
[Sub-task] Implement changes to CSS

### ISSUE THREAD

**Issue by OlgaOrtiz** [OlgaOrtiz/Nekos-Magic-Converter#24]
# What do we need?
Change all the CSS of the website so it would match the new style

# Acceptance Criterial
 - [ ] The general CSS is working properly
 - [ ] The converter CSS is working properly 
 - [ ] The desktop version is correct
 - [ ] The mobile version is correct
 - [ ] The tablet version is correct
