### ISSUE TITLE
[Sub-task] Refactor the weight convertion logic

### ISSUE THREAD

**Issue by Yifei-G** [OlgaOrtiz/Nekos-Magic-Converter#6]
# What do we need?
This is the sub-task of the  [convertion logic refactoring ticket](https://github.com/OlgaOrtiz/Converter/issues/5)

In this sub-task, we need to add all the weight related convertion logic into the weightConverter.js file. 
Createting 6 function which each of them in charges with a different weight convertion:

 1. lbToKilo ---> when the input is lb and user wants to convert to kg
 2. lbToTon ----> When the input is lb and user wants to convert to t
 3. kgToPound ----> When the input is kg and user wants to convert to lb
 4. kgToTon -----> When the input is kg and user wants to convert to t
 5. tToKilo ------> When the input is t and user wants to convert to kg
 6. tToPound ----> When the input is t and user wants to convert to t

# Acceptance Criterial

 - [ ]  The new functions should work exactly as before the refactoring
 - [ ]  When user inputs a numeric value and select lb as input unit and kg as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [ ] When user inputs a numeric value and select lb as input unit and t as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [ ] When user inputs a numeric value and select kg as input unit and lb as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [ ] When user inputs a numeric value and select kg as input unit and t as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [ ] When user inputs a numeric value and select t as input unit and kg as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [ ] When user inputs a numeric value and select t as input unit and lb as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
