### ISSUE TITLE
[Sub-task] Refactor the distance convertion logic

### ISSUE THREAD

**Issue by Yifei-G** [OlgaOrtiz/Nekos-Magic-Converter#7]
# What do we need?
This is the sub-task of the  [convertion logic refactoring ticket](https://github.com/OlgaOrtiz/Converter/issues/5)

In this sub-task, we need to add all the distance related convertion logic into the distanceConverter.js file. 
Createting 6 function which each of them in charges with a different weight convertion:

 1. mToFeet ---> when the input is m and user wants to convert to ft
 2. mToYard ----> When the input is m and user wants to convert to yd
 3. ftToMeter ----> When the input is ft and user wants to convert to m
 4. ftToYard -----> When the input is ft and user wants to convert to yd
 5. ydToMeter ------> When the input is yd and user wants to convert to m
 6. ydToFeet ----> When the input is yd and user wants to convert to ft

# Acceptance Criterial

 - [x]  The new functions should work exactly as before the refactoring
 - [x]  When user inputs a numeric value and select m as input unit and ft as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select m as input unit and yd as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select ft as input unit and m as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select ft as input unit and yd as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select yd as input unit and m as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select yd as input unit and ft as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
