### ISSUE TITLE
[Sub-task] Refactor the temperature convertion logic

### ISSUE THREAD

**Issue by Yifei-G** [OlgaOrtiz/Nekos-Magic-Converter#8]
# What do we need?
This is the sub-task of the  [convertion logic refactoring ticket](https://github.com/OlgaOrtiz/Converter/issues/5)

In this sub-task, we need to add all the distance related convertion logic into the distanceConverter.js file. 
Createting 6 function which each of them in charges with a different weight convertion:

 1. CToFahrenheit ---> when the input is C and user wants to convert to F
 2. CToKelvin ----> When the input is C and user wants to convert to K
 3. FToCelcius ----> When the input is F and user wants to convert to C
 4. FToKelvin -----> When the input is F and user wants to convert to K
 5. KToCelcius ------> When the input is K and user wants to convert to C
 6. KToFahrenheit ----> When the input is K and user wants to convert to F

# Acceptance Criterial

 - [x]  The new functions should work exactly as before the refactoring
 - [x]  When user inputs a numeric value and select C as input unit and F as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select C as input unit and K as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select F as input unit and C as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select F as input unit and K as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select K as input unit and C as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
 - [x] When user inputs a numeric value and select K as input unit and F as output unit, when the user clicks convert button, he/she will be able to get the corresponding value
